export const queryKeys = {
    systemStatus: ["system-status"],
    gameweeks: ["gameweeks"],
    teams: ["teams"],
    players: (leagueId) => ["players", leagueId ?? "no-league"],
    teamFixtures: (teamId) => ["fixtures", "team", teamId],
    allFixtures: ["fixtures", "all"],
    watchlist: (userId, leagueId) => ["watchlist", userId, leagueId],
    squad: (userId, gameweekId) => ["squad", userId, gameweekId],
    squadPlayerData: (userId, gameweekId) => ["squad-player-data", userId, gameweekId],
    userChips: (userId) => ["user-chips", userId],
    waiverPlan: (gameweekId) => ["waiver-plan", gameweekId],
    irWaiverPlan: (gameweekId) => ["ir-waiver-plan", gameweekId],
    pointsPage: (userId, gameweekId, live) => ["points-page", userId, gameweekId, live ? "live" : "final"],
    leagueUsers: (leagueId) => ["league-users", leagueId],
    currentLeague: (leagueId) => ["current-league", leagueId],
    maintenanceLeague: (leagueId) => ["maintenance-league", leagueId],
    leagueStandings: (leagueId) => ["league-standings", leagueId],
    transferWindow: (leagueId) => ["transfer-window", leagueId],
    tradeContext: (leagueId) => ["trades", "context", leagueId],
    trades: (leagueId) => ["trades", "offers", leagueId],
    transferEvent: (leagueId) => ["transfer-event", leagueId],
    transferHistory: (leagueId, gameweekId) => ["transfer-history", leagueId, gameweekId],
    transferOrder: (leagueId, gameweekId) => ["transfer-order", leagueId, gameweekId],
    transferAttendance: (leagueId, gameweekId, userId) => ["transfer-attendance", leagueId, gameweekId, userId],
    draftConfig: (leagueId) => ["draft-config", leagueId],
    userGameweekPoints: (userId, gameweekId) => ["user-points", userId, gameweekId],
    userTotalPoints: (userId) => ["user-total-points", userId],
    dailyStatus: (gameweekId) => ["daily-status", gameweekId],
    gameweekRoast: (gameweekId) => ["ai-roast", "gameweek", gameweekId],
    alexCoach: (gameweekId) => ["alex-coach", "gameweek", gameweekId],
    dreamTeam: (gameweekId) => ["dream-team", gameweekId],
    scoringDefaults: ["scoring-rules", "defaults"],
    playerStats: (playerId) => ["player-stats", playerId],
    playerMatch: (playerId, gameweekId, userId) => ["player-match", playerId, gameweekId, userId],
    pointsHistory: (userId) => ["points-history", userId],
    irStatus: ["ir-status"],
    playersOfTheWeek: (userId) => ["players-of-the-week", userId],
    adminAssists: (leagueId, gameweekId) => ["admin-assists", leagueId ?? "current", gameweekId],
    adminPenalties: (leagueId, gameweekId) => ["admin-penalties", leagueId ?? "current", gameweekId],
    lockedPlayers: (leagueId) => ["locked-players", leagueId ?? "current"],
    adminUsers: ["admin-users"],
    adminUserDetails: (userId) => ["admin-user-details", userId],
    maintenanceLeagues: ["maintenance-leagues"],
    adminPlayers: ["admin-players"],
};
