CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    registered_at TIMESTAMP NOT NULL
);

CREATE TABLE leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    league_code VARCHAR(12) NOT NULL UNIQUE,
    admin_id INTEGER REFERENCES users(id)
);

CREATE TABLE league_users (
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (league_id, user_id)
);

CREATE TABLE teams (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    short_name VARCHAR(255)
);

-- state and owner_id are intentionally present in the baseline so installations
-- upgraded through V1/V2 can preserve old locks before V5 removes global ownership.
CREATE TABLE players (
    id INTEGER PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    view_name VARCHAR(255),
    position VARCHAR(16),
    team_id INTEGER,
    state VARCHAR(16),
    owner_id INTEGER,
    injured BOOLEAN NOT NULL DEFAULT FALSE,
    total_points INTEGER NOT NULL DEFAULT 0,
    news VARCHAR(255),
    chance_of_playing_this_round INTEGER,
    chance_of_playing_next_round INTEGER,
    news_added TIMESTAMP,
    photo VARCHAR(255)
);

CREATE TABLE gameweeks (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    first_kickoff_time TIMESTAMP,
    last_kickoff_time TIMESTAMP,
    status VARCHAR(255),
    transfer_open_time TIMESTAMP,
    calculated BOOLEAN NOT NULL DEFAULT FALSE,
    transfer_window_processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE fixtures (
    id INTEGER PRIMARY KEY,
    gameweek_id INTEGER NOT NULL,
    home_team_id INTEGER NOT NULL,
    away_team_id INTEGER NOT NULL,
    home_difficulty INTEGER,
    away_difficulty INTEGER,
    kickoff_time TIMESTAMP,
    started BOOLEAN NOT NULL DEFAULT FALSE,
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    minutes INTEGER NOT NULL DEFAULT 0,
    score_home INTEGER,
    score_away INTEGER
);

CREATE TABLE player_gameweek_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER REFERENCES players(id),
    gameweek INTEGER NOT NULL,
    opponent_team_id INTEGER NOT NULL DEFAULT 0,
    was_home BOOLEAN NOT NULL DEFAULT FALSE,
    minutes_played INTEGER NOT NULL DEFAULT 0,
    goals INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    goals_conceded INTEGER NOT NULL DEFAULT 0,
    clean_sheet BOOLEAN NOT NULL DEFAULT FALSE,
    clean_sheet30 BOOLEAN NOT NULL DEFAULT FALSE,
    clean_sheet45 BOOLEAN NOT NULL DEFAULT FALSE,
    clean_sheet60 BOOLEAN NOT NULL DEFAULT FALSE,
    yellow_cards INTEGER NOT NULL DEFAULT 0,
    red_cards INTEGER NOT NULL DEFAULT 0,
    penalties_saved INTEGER NOT NULL DEFAULT 0,
    penalties_missed INTEGER NOT NULL DEFAULT 0,
    penalties_conceded INTEGER NOT NULL DEFAULT 0,
    own_goals INTEGER NOT NULL DEFAULT 0,
    started BOOLEAN NOT NULL DEFAULT FALSE,
    total_points INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_player_gameweek_stats UNIQUE (player_id, gameweek)
);

CREATE TABLE player_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(id),
    gameweek INTEGER NOT NULL,
    points INTEGER NOT NULL,
    CONSTRAINT uk_player_points UNIQUE (player_id, gameweek)
);

CREATE TABLE user_game_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(id),
    fantasy_team_name VARCHAR(255),
    total_points INTEGER NOT NULL DEFAULT 0,
    current_squad_id BIGINT UNIQUE,
    next_squad_id BIGINT UNIQUE
);

CREATE TABLE user_squads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES user_game_data(id),
    gameweek INTEGER NOT NULL,
    captain_id INTEGER,
    vice_captain_id INTEGER,
    first_pick_id INTEGER,
    ir_id INTEGER,
    auto_subs_applied BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_user_squad_gameweek UNIQUE (user_id, gameweek)
);

ALTER TABLE user_game_data
    ADD CONSTRAINT fk_user_game_data_current_squad
        FOREIGN KEY (current_squad_id) REFERENCES user_squads(id);
ALTER TABLE user_game_data
    ADD CONSTRAINT fk_user_game_data_next_squad
        FOREIGN KEY (next_squad_id) REFERENCES user_squads(id);

CREATE TABLE user_squad_starting (
    squad_id BIGINT NOT NULL REFERENCES user_squads(id) ON DELETE CASCADE,
    player_id INTEGER
);

CREATE TABLE user_squad_bench (
    squad_id BIGINT NOT NULL REFERENCES user_squads(id) ON DELETE CASCADE,
    slot_name VARCHAR(255) NOT NULL,
    player_id INTEGER,
    PRIMARY KEY (squad_id, slot_name)
);

CREATE TABLE user_squad_formation (
    squad_id BIGINT NOT NULL REFERENCES user_squads(id) ON DELETE CASCADE,
    position VARCHAR(255) NOT NULL,
    count INTEGER,
    PRIMARY KEY (squad_id, position)
);

CREATE TABLE user_chips (
    user_id INTEGER NOT NULL REFERENCES user_game_data(id) ON DELETE CASCADE,
    chip_name VARCHAR(255) NOT NULL,
    count INTEGER,
    PRIMARY KEY (user_id, chip_name)
);

CREATE TABLE user_active_chips (
    user_id INTEGER NOT NULL REFERENCES user_game_data(id) ON DELETE CASCADE,
    chip_name VARCHAR(255) NOT NULL,
    active BOOLEAN,
    PRIMARY KEY (user_id, chip_name)
);

CREATE TABLE user_watched_players (
    user_id INTEGER NOT NULL REFERENCES user_game_data(id) ON DELETE CASCADE,
    player_id INTEGER
);

CREATE TABLE user_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES user_game_data(id),
    gameweek INTEGER NOT NULL,
    points INTEGER NOT NULL,
    CONSTRAINT uk_user_points UNIQUE (user_id, gameweek)
);

CREATE TABLE gameweek_daily_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gameweek_id INTEGER NOT NULL,
    match_date DATE NOT NULL,
    is_calculated BOOLEAN NOT NULL DEFAULT FALSE,
    calculated_at TIMESTAMP,
    CONSTRAINT uk_daily_gameweek_date UNIQUE (gameweek_id, match_date)
);

CREATE TABLE gameweek_transfer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gameweek_id INTEGER REFERENCES gameweeks(id),
    position INTEGER NOT NULL,
    user_id INTEGER
);
