ALTER TABLE waiver_preferences
    ADD COLUMN IF NOT EXISTS plan_type VARCHAR(16) NOT NULL DEFAULT 'REGULAR';

ALTER TABLE waiver_preferences
    DROP CONSTRAINT IF EXISTS uk_waiver_user_gw_priority;

ALTER TABLE waiver_preferences
    ADD CONSTRAINT uk_waiver_user_gw_type_priority
        UNIQUE (league_id, user_id, gameweek_id, plan_type, priority);

CREATE TABLE IF NOT EXISTS waiver_plan_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    gameweek_id INTEGER NOT NULL REFERENCES gameweeks(id) ON DELETE CASCADE,
    next_priority INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT uk_waiver_progress_user_gw
        UNIQUE (league_id, user_id, gameweek_id)
);

CREATE TABLE IF NOT EXISTS league_transfer_window_canonical_order (
    window_id BIGINT NOT NULL REFERENCES league_transfer_windows(id) ON DELETE CASCADE,
    turn_position INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (window_id, turn_position)
);

INSERT INTO league_transfer_window_canonical_order (window_id, turn_position, user_id)
SELECT current_order.window_id, current_order.turn_position, current_order.user_id
FROM league_transfer_window_order AS current_order
WHERE NOT EXISTS (
    SELECT 1
    FROM league_transfer_window_canonical_order AS canonical
    WHERE canonical.window_id = current_order.window_id
);
