ALTER TABLE user_game_data
    ADD COLUMN IF NOT EXISTS team_logo_data TEXT;

ALTER TABLE user_game_data
    ADD COLUMN IF NOT EXISTS team_logo_content_type VARCHAR(50);

ALTER TABLE user_game_data
    ADD COLUMN IF NOT EXISTS team_logo_version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS player_fixture_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    fixture_id INTEGER NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    gameweek INTEGER NOT NULL,
    opponent_team_id INTEGER NOT NULL DEFAULT 0,
    was_home BOOLEAN NOT NULL DEFAULT FALSE,
    minutes_played INTEGER NOT NULL DEFAULT 0,
    goals INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    goals_conceded INTEGER NOT NULL DEFAULT 0,
    yellow_cards INTEGER NOT NULL DEFAULT 0,
    red_cards INTEGER NOT NULL DEFAULT 0,
    penalties_saved INTEGER NOT NULL DEFAULT 0,
    penalties_missed INTEGER NOT NULL DEFAULT 0,
    own_goals INTEGER NOT NULL DEFAULT 0,
    started BOOLEAN NOT NULL DEFAULT FALSE,
    total_points INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_player_fixture_stats UNIQUE (player_id, fixture_id)
);
