CREATE TABLE IF NOT EXISTS auto_substitutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    squad_id BIGINT NOT NULL REFERENCES user_squads(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    player_in_id INTEGER NOT NULL REFERENCES players(id),
    player_out_id INTEGER NOT NULL REFERENCES players(id),
    CONSTRAINT uk_auto_substitution_squad_sequence UNIQUE (squad_id, sequence_number)
);

CREATE INDEX IF NOT EXISTS ix_auto_substitution_squad
    ON auto_substitutions (squad_id, sequence_number);
