ALTER TABLE users ADD COLUMN email VARCHAR(320);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Existing development accounts remain usable after this migration. New
-- registrations always provide and verify a real email address.
UPDATE users
SET email = 'legacy-' || id || '@invalid.local',
    email_verified = TRUE
WHERE email IS NULL;

ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);

CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    token_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP
);

CREATE INDEX idx_auth_tokens_user_type ON auth_tokens(user_id, token_type);
CREATE INDEX idx_auth_tokens_expiry ON auth_tokens(expires_at);
