CREATE TABLE ai_roasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    gameweek INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_roasts_user
        FOREIGN KEY (user_id) REFERENCES user_game_data(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_roasts_gameweek
        FOREIGN KEY (gameweek) REFERENCES gameweeks(id) ON DELETE CASCADE,
    CONSTRAINT uk_ai_roasts_user_gameweek UNIQUE (user_id, gameweek)
);

