ALTER TABLE leagues
    ADD COLUMN IF NOT EXISTS max_participants INTEGER NOT NULL DEFAULT 8;

CREATE UNIQUE INDEX IF NOT EXISTS uk_leagues_league_code
    ON leagues (league_code);

CREATE TABLE IF NOT EXISTS league_scoring_rules (
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    rule_key VARCHAR(80) NOT NULL,
    points INTEGER NOT NULL,
    PRIMARY KEY (league_id, rule_key)
);

ALTER TABLE user_game_data
    ADD COLUMN IF NOT EXISTS league_id BIGINT;

UPDATE user_game_data AS game_data
SET league_id = (
    SELECT MIN(membership.league_id)
    FROM league_users AS membership
    WHERE membership.user_id = game_data.user_id
)
WHERE game_data.league_id IS NULL;

CREATE INDEX IF NOT EXISTS ix_user_game_data_league
    ON user_game_data (league_id);

INSERT INTO league_scoring_rules (league_id, rule_key, points)
SELECT league.id, defaults.rule_key, defaults.points
FROM leagues AS league
CROSS JOIN (
    VALUES
        ('GOAL.GOALKEEPER', 10),
        ('GOAL.DEFENDER', 6),
        ('GOAL.MIDFIELDER', 5),
        ('GOAL.FORWARD', 4),
        ('ASSIST.ALL', 3),
        ('YELLOW_CARD.ALL', -1),
        ('RED_CARD.ALL', -5),
        ('PLAYED.ALL', 2),
        ('FROM_BENCH.ALL', 1),
        ('OWN_GOAL.ALL', -2),
        ('PENALTY_SAVE.GOALKEEPER', 5),
        ('PENALTY_MISS.GOALKEEPER', -10),
        ('PENALTY_MISS.DEFENDER', -6),
        ('PENALTY_MISS.MIDFIELDER', -5),
        ('PENALTY_MISS.FORWARD', -4),
        ('PENALTY_CONCEDED.ALL', -2),
        ('SECOND_GOAL_BONUS.FORWARD', 1),
        ('CLEAN_SHEET_30.GOALKEEPER', 2),
        ('CLEAN_SHEET_46.GOALKEEPER', 3),
        ('CLEAN_SHEET_60.GOALKEEPER', 5),
        ('CLEAN_SHEET_30.DEFENDER', 1),
        ('CLEAN_SHEET_46.DEFENDER', 2),
        ('CLEAN_SHEET_60.DEFENDER', 4),
        ('CLEAN_SHEET_30.MIDFIELDER', 0),
        ('CLEAN_SHEET_46.MIDFIELDER', 0),
        ('CLEAN_SHEET_60.MIDFIELDER', 1),
        ('CLEAN_SHEET_30.FORWARD', 0),
        ('CLEAN_SHEET_46.FORWARD', 0),
        ('CLEAN_SHEET_60.FORWARD', 0),
        ('GOAL_CONCEDED_AFTER_2.GOALKEEPER', -1),
        ('GOAL_CONCEDED_AFTER_2.DEFENDER', -1)
) AS defaults(rule_key, points)
WHERE NOT EXISTS (
    SELECT 1
    FROM league_scoring_rules AS existing
    WHERE existing.league_id = league.id
      AND existing.rule_key = defaults.rule_key
);

CREATE TABLE IF NOT EXISTS league_transfer_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    gameweek_id INTEGER NOT NULL REFERENCES gameweeks(id) ON DELETE CASCADE,
    window_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    phase VARCHAR(16) NOT NULL,
    regular_cursor INTEGER NOT NULL DEFAULT 0,
    ir_cursor INTEGER NOT NULL DEFAULT 0,
    opened_at TIMESTAMP,
    closed_at TIMESTAMP,
    turn_started_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_transfer_window_league_gw_type
        UNIQUE (league_id, gameweek_id, window_type)
);

CREATE INDEX IF NOT EXISTS ix_transfer_window_league_status
    ON league_transfer_windows (league_id, status);

CREATE TABLE IF NOT EXISTS league_transfer_window_order (
    window_id BIGINT NOT NULL REFERENCES league_transfer_windows(id) ON DELETE CASCADE,
    turn_position INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (window_id, turn_position)
);

CREATE TABLE IF NOT EXISTS league_transfer_window_ir_order (
    window_id BIGINT NOT NULL REFERENCES league_transfer_windows(id) ON DELETE CASCADE,
    turn_position INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (window_id, turn_position)
);

CREATE TABLE IF NOT EXISTS league_draft_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL UNIQUE REFERENCES leagues(id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP,
    processed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS waiver_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    gameweek_id INTEGER NOT NULL REFERENCES gameweeks(id) ON DELETE CASCADE,
    priority INTEGER NOT NULL,
    player_in_id INTEGER NOT NULL REFERENCES players(id),
    player_out_id INTEGER NOT NULL REFERENCES players(id),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_waiver_user_gw_priority
        UNIQUE (league_id, user_id, gameweek_id, priority)
);

CREATE INDEX IF NOT EXISTS ix_waiver_lookup
    ON waiver_preferences (league_id, user_id, gameweek_id, priority);

UPDATE players
SET owner_id = -1,
    state = 'NONE'
WHERE state IS NULL OR state <> 'LOCKED';
