CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    p256dh VARCHAR(512) NOT NULL,
    auth_secret VARCHAR(512) NOT NULL,
    client_instance_id VARCHAR(128),
    expiration_time BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    last_success_at TIMESTAMP,
    disabled_at TIMESTAMP,
    CONSTRAINT fk_push_subscription_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_subscriptions_user_enabled
    ON push_subscriptions(user_id, disabled_at);

CREATE TABLE notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(160) NOT NULL,
    user_id INTEGER NOT NULL,
    channel VARCHAR(24) NOT NULL,
    delivered_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_delivery_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_notification_delivery_event_user UNIQUE (event_id, user_id)
);

CREATE INDEX idx_notification_deliveries_time ON notification_deliveries(delivered_at);
