ALTER TABLE ai_roasts ADD COLUMN league_id BIGINT;
ALTER TABLE ai_roasts ADD COLUMN rotation_index INTEGER NOT NULL DEFAULT 0;

UPDATE ai_roasts r
SET league_id = (SELECT u.league_id FROM user_game_data u WHERE u.id = r.user_id);

DELETE FROM ai_roasts WHERE league_id IS NULL;
ALTER TABLE ai_roasts ALTER COLUMN league_id SET NOT NULL;

ALTER TABLE ai_roasts DROP CONSTRAINT uk_ai_roasts_user_gameweek;
ALTER TABLE ai_roasts ADD CONSTRAINT fk_ai_roasts_league
    FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE;
ALTER TABLE ai_roasts ADD CONSTRAINT uk_ai_roasts_league_gameweek_target
    UNIQUE (league_id, gameweek, user_id);
CREATE INDEX idx_ai_roasts_league_gameweek_rotation
    ON ai_roasts (league_id, gameweek, rotation_index);

ALTER TABLE players ADD COLUMN form DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN points_per_game DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN selected_by_percent DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN expected_goals DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN expected_assists DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN expected_goal_involvements DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN expected_goals_conceded DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN influence DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN creativity DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN threat DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN ict_index DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN now_cost INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN metrics_updated_at TIMESTAMP;

CREATE TABLE ai_coach_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    league_id BIGINT NOT NULL,
    gameweek INTEGER NOT NULL,
    snapshot_hash VARCHAR(96) NOT NULL,
    analysis_json TEXT NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    data_as_of TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_coach_threads_user FOREIGN KEY (user_id) REFERENCES user_game_data(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_coach_threads_league FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_coach_threads_gameweek FOREIGN KEY (gameweek) REFERENCES gameweeks(id) ON DELETE CASCADE,
    CONSTRAINT uk_ai_coach_threads_user_gameweek UNIQUE (user_id, gameweek)
);

CREATE TABLE ai_coach_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_coach_messages_thread FOREIGN KEY (thread_id) REFERENCES ai_coach_threads(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_coach_messages_thread_created
    ON ai_coach_messages (thread_id, created_at);

CREATE TABLE ai_coach_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    gameweek INTEGER NOT NULL,
    usage_type VARCHAR(24) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ai_coach_usage_user FOREIGN KEY (user_id) REFERENCES user_game_data(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_coach_usage_gameweek FOREIGN KEY (gameweek) REFERENCES gameweeks(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_coach_usage_user_type_created
    ON ai_coach_usage (user_id, usage_type, created_at);
