CREATE TABLE trade_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    proposer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_trade_offer_distinct_users CHECK (proposer_user_id <> recipient_user_id)
);

CREATE TABLE trade_offer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES trade_offers(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    proposer_player_id INTEGER NOT NULL REFERENCES players(id),
    recipient_player_id INTEGER NOT NULL REFERENCES players(id),
    CONSTRAINT uq_trade_offer_item_order UNIQUE (offer_id, sort_order)
);

CREATE INDEX idx_trade_offers_recipient_status
    ON trade_offers(recipient_user_id, status, created_at DESC);
CREATE INDEX idx_trade_offers_proposer_status
    ON trade_offers(proposer_user_id, status, created_at DESC);
CREATE INDEX idx_trade_offers_league_status
    ON trade_offers(league_id, status, created_at DESC);
CREATE INDEX idx_trade_offer_items_offer
    ON trade_offer_items(offer_id);

