ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS code INTEGER;

CREATE TABLE IF NOT EXISTS league_transfer_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    gameweek_id INTEGER NOT NULL REFERENCES gameweeks(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    window_type VARCHAR(16) NOT NULL,
    source VARCHAR(16) NOT NULL,
    player_in_id INTEGER NOT NULL REFERENCES players(id),
    player_out_id INTEGER REFERENCES players(id),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_transfer_action_league_gw
    ON league_transfer_actions (league_id, gameweek_id, id);
