ALTER TABLE players ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMP;

UPDATE players
SET first_seen_at = CURRENT_TIMESTAMP
WHERE first_seen_at IS NULL;

ALTER TABLE league_transfer_windows
    ALTER COLUMN window_type SET DATA TYPE VARCHAR(24);

ALTER TABLE league_draft_config
    ADD COLUMN IF NOT EXISTS draft_type VARCHAR(24) DEFAULT 'INITIAL' NOT NULL;

ALTER TABLE league_draft_config
    ADD COLUMN IF NOT EXISTS order_source VARCHAR(24) DEFAULT 'TRANSFER_ORDER' NOT NULL;

CREATE TABLE IF NOT EXISTS league_draft_config_order (
    config_id BIGINT NOT NULL,
    pick_position INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (config_id, pick_position),
    CONSTRAINT fk_draft_config_order_config
        FOREIGN KEY (config_id) REFERENCES league_draft_config(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS league_supplemental_draft_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL,
    player_id INTEGER NOT NULL,
    discovered_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_supplemental_pool_league_player UNIQUE (league_id, player_id),
    CONSTRAINT fk_supplemental_pool_league
        FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE,
    CONSTRAINT fk_supplemental_pool_player
        FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_supplemental_pool_league
    ON league_supplemental_draft_pool(league_id);
